#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 5424026
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : klickety
Version  : 24.12.0
Release  : 76
URL      : https://download.kde.org/stable/release-service/24.12.0/src/klickety-24.12.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.12.0/src/klickety-24.12.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.12.0/src/klickety-24.12.0.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GFDL-1.2 GPL-2.0
Requires: klickety-bin = %{version}-%{release}
Requires: klickety-data = %{version}-%{release}
Requires: klickety-license = %{version}-%{release}
Requires: klickety-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : ki18n-dev
BuildRequires : kio-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Klickety used KNotify with just two standard KDE sounds.
I ported it to KGameSound but just copied those used
standard KDE sounds into Klickety. Here is what was copied:

%package bin
Summary: bin components for the klickety package.
Group: Binaries
Requires: klickety-data = %{version}-%{release}
Requires: klickety-license = %{version}-%{release}

%description bin
bin components for the klickety package.


%package data
Summary: data components for the klickety package.
Group: Data

%description data
data components for the klickety package.


%package doc
Summary: doc components for the klickety package.
Group: Documentation

%description doc
doc components for the klickety package.


%package license
Summary: license components for the klickety package.
Group: Default

%description license
license components for the klickety package.


%package locales
Summary: locales components for the klickety package.
Group: Default

%description locales
locales components for the klickety package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n klickety-24.12.0
cd %{_builddir}/klickety-24.12.0
pushd ..
cp -a klickety-24.12.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735219214
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735219214
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/klickety
cp %{_builddir}/klickety-%{version}/CMakePresets.json.license %{buildroot}/usr/share/package-licenses/klickety/29fb05b49e12a380545499938c4879440bd8851e || :
cp %{_builddir}/klickety-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/klickety/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/klickety-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/klickety/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/klickety-%{version}/LICENSES/GFDL-1.2-or-later.txt %{buildroot}/usr/share/package-licenses/klickety/7697008f58568e61e7598e796eafc2a997503fde || :
cp %{_builddir}/klickety-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/klickety/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang klickety
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/klickety
/usr/bin/klickety

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.klickety.desktop
/usr/share/applications/org.kde.ksame.desktop
/usr/share/icons/hicolor/128x128/apps/klickety.png
/usr/share/icons/hicolor/128x128/apps/ksame.png
/usr/share/icons/hicolor/16x16/apps/klickety.png
/usr/share/icons/hicolor/16x16/apps/ksame.png
/usr/share/icons/hicolor/22x22/apps/klickety.png
/usr/share/icons/hicolor/22x22/apps/ksame.png
/usr/share/icons/hicolor/32x32/apps/klickety.png
/usr/share/icons/hicolor/32x32/apps/ksame.png
/usr/share/icons/hicolor/48x48/apps/klickety.png
/usr/share/icons/hicolor/48x48/apps/ksame.png
/usr/share/icons/hicolor/64x64/apps/klickety.png
/usr/share/icons/hicolor/64x64/apps/ksame.png
/usr/share/kconf_update/klickety-2.0-inherit-ksame-highscore.pl
/usr/share/kconf_update/klickety.upd
/usr/share/klickety/klickety.kcfg
/usr/share/klickety/themes/classic.svgz
/usr/share/klickety/themes/classic_preview.png
/usr/share/klickety/themes/default.desktop
/usr/share/klickety/themes/ksame.desktop
/usr/share/klickety/themes/ksame.svgz
/usr/share/klickety/themes/ksame_old.desktop
/usr/share/klickety/themes/ksame_old.svgz
/usr/share/klickety/themes/ksame_old_preview.png
/usr/share/klickety/themes/ksame_preview.png
/usr/share/metainfo/org.kde.klickety.appdata.xml
/usr/share/metainfo/org.kde.ksame.appdata.xml
/usr/share/sounds/klickety/game-finished.ogg
/usr/share/sounds/klickety/remove.ogg

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/klickety/config-background.png
/usr/share/doc/HTML/ca/klickety/config-customgame.png
/usr/share/doc/HTML/ca/klickety/config-general.png
/usr/share/doc/HTML/ca/klickety/config-theme.png
/usr/share/doc/HTML/ca/klickety/gamescreen.png
/usr/share/doc/HTML/ca/klickety/index.cache.bz2
/usr/share/doc/HTML/ca/klickety/index.docbook
/usr/share/doc/HTML/ca/klickety/numbered.png
/usr/share/doc/HTML/de/klickety/index.cache.bz2
/usr/share/doc/HTML/de/klickety/index.docbook
/usr/share/doc/HTML/en/klickety/config-background.png
/usr/share/doc/HTML/en/klickety/config-customgame.png
/usr/share/doc/HTML/en/klickety/config-general.png
/usr/share/doc/HTML/en/klickety/config-theme.png
/usr/share/doc/HTML/en/klickety/gamescreen.png
/usr/share/doc/HTML/en/klickety/highscore.png
/usr/share/doc/HTML/en/klickety/index.cache.bz2
/usr/share/doc/HTML/en/klickety/index.docbook
/usr/share/doc/HTML/en/klickety/ksamemode.png
/usr/share/doc/HTML/en/klickety/numbered.png
/usr/share/doc/HTML/es/klickety/index.cache.bz2
/usr/share/doc/HTML/es/klickety/index.docbook
/usr/share/doc/HTML/et/klickety/index.cache.bz2
/usr/share/doc/HTML/et/klickety/index.docbook
/usr/share/doc/HTML/fr/klickety/config-background.png
/usr/share/doc/HTML/fr/klickety/config-customgame.png
/usr/share/doc/HTML/fr/klickety/config-general.png
/usr/share/doc/HTML/fr/klickety/config-theme.png
/usr/share/doc/HTML/fr/klickety/gamescreen.png
/usr/share/doc/HTML/fr/klickety/highscore.png
/usr/share/doc/HTML/fr/klickety/index.cache.bz2
/usr/share/doc/HTML/fr/klickety/index.docbook
/usr/share/doc/HTML/fr/klickety/ksamemode.png
/usr/share/doc/HTML/fr/klickety/numbered.png
/usr/share/doc/HTML/fr/klickety/shortcuts.png
/usr/share/doc/HTML/it/klickety/index.cache.bz2
/usr/share/doc/HTML/it/klickety/index.docbook
/usr/share/doc/HTML/nl/klickety/index.cache.bz2
/usr/share/doc/HTML/nl/klickety/index.docbook
/usr/share/doc/HTML/pt/klickety/index.cache.bz2
/usr/share/doc/HTML/pt/klickety/index.docbook
/usr/share/doc/HTML/pt_BR/klickety/index.cache.bz2
/usr/share/doc/HTML/pt_BR/klickety/index.docbook
/usr/share/doc/HTML/sl/klickety/index.cache.bz2
/usr/share/doc/HTML/sl/klickety/index.docbook
/usr/share/doc/HTML/sv/klickety/index.cache.bz2
/usr/share/doc/HTML/sv/klickety/index.docbook
/usr/share/doc/HTML/uk/klickety/config-background.png
/usr/share/doc/HTML/uk/klickety/config-customgame.png
/usr/share/doc/HTML/uk/klickety/config-general.png
/usr/share/doc/HTML/uk/klickety/config-theme.png
/usr/share/doc/HTML/uk/klickety/gamescreen.png
/usr/share/doc/HTML/uk/klickety/highscore.png
/usr/share/doc/HTML/uk/klickety/index.cache.bz2
/usr/share/doc/HTML/uk/klickety/index.docbook
/usr/share/doc/HTML/uk/klickety/ksamemode.png
/usr/share/doc/HTML/uk/klickety/numbered.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/klickety/29fb05b49e12a380545499938c4879440bd8851e
/usr/share/package-licenses/klickety/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/klickety/7697008f58568e61e7598e796eafc2a997503fde
/usr/share/package-licenses/klickety/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/klickety/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c

%files locales -f klickety.lang
%defattr(-,root,root,-)

