#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : klickety
Version  : 19.04.1
Release  : 8
URL      : https://download.kde.org/stable/applications/19.04.1/src/klickety-19.04.1.tar.xz
Source0  : https://download.kde.org/stable/applications/19.04.1/src/klickety-19.04.1.tar.xz
Source99 : https://download.kde.org/stable/applications/19.04.1/src/klickety-19.04.1.tar.xz.sig
Summary  : An adaptation of the Clickomania game
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : qtbase-dev mesa-dev

%description
Klickety used KNotify with just two standard KDE sounds.
I ported it to KgSound but just copied those used
standard KDE sounds into Klickety. Here is what was copied:

%prep
%setup -q -n klickety-19.04.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557446582
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1557446582
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/klickety
cp COPYING %{buildroot}/usr/share/package-licenses/klickety/COPYING
cp COPYING.DOC %{buildroot}/usr/share/package-licenses/klickety/COPYING.DOC
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
